export interface LatexCompletion {
  label: string;
  insertText: string;
  detail?: string;
}

export const LATEX_COMPLETIONS: LatexCompletion[] = [
  // -- Greek lowercase --
  { label: '\\alpha', insertText: '\\alpha' },
  { label: '\\beta', insertText: '\\beta' },
  { label: '\\gamma', insertText: '\\gamma' },
  { label: '\\delta', insertText: '\\delta' },
  { label: '\\epsilon', insertText: '\\epsilon' },
  { label: '\\varepsilon', insertText: '\\varepsilon' },
  { label: '\\zeta', insertText: '\\zeta' },
  { label: '\\eta', insertText: '\\eta' },
  { label: '\\theta', insertText: '\\theta' },
  { label: '\\vartheta', insertText: '\\vartheta' },
  { label: '\\iota', insertText: '\\iota' },
  { label: '\\kappa', insertText: '\\kappa' },
  { label: '\\lambda', insertText: '\\lambda' },
  { label: '\\mu', insertText: '\\mu' },
  { label: '\\nu', insertText: '\\nu' },
  { label: '\\xi', insertText: '\\xi' },
  { label: '\\pi', insertText: '\\pi' },
  { label: '\\varpi', insertText: '\\varpi' },
  { label: '\\rho', insertText: '\\rho' },
  { label: '\\varrho', insertText: '\\varrho' },
  { label: '\\sigma', insertText: '\\sigma' },
  { label: '\\varsigma', insertText: '\\varsigma' },
  { label: '\\tau', insertText: '\\tau' },
  { label: '\\upsilon', insertText: '\\upsilon' },
  { label: '\\phi', insertText: '\\phi' },
  { label: '\\varphi', insertText: '\\varphi' },
  { label: '\\chi', insertText: '\\chi' },
  { label: '\\psi', insertText: '\\psi' },
  { label: '\\omega', insertText: '\\omega' },

  // -- Greek uppercase --
  { label: '\\Gamma', insertText: '\\Gamma' },
  { label: '\\Delta', insertText: '\\Delta' },
  { label: '\\Theta', insertText: '\\Theta' },
  { label: '\\Lambda', insertText: '\\Lambda' },
  { label: '\\Xi', insertText: '\\Xi' },
  { label: '\\Pi', insertText: '\\Pi' },
  { label: '\\Sigma', insertText: '\\Sigma' },
  { label: '\\Phi', insertText: '\\Phi' },
  { label: '\\Psi', insertText: '\\Psi' },
  { label: '\\Omega', insertText: '\\Omega' },

  // -- Fractions and roots --
  { label: '\\frac', insertText: '\\frac{${1:num}}{${2:den}}', detail: 'Fraction' },
  { label: '\\sqrt', insertText: '\\sqrt{${1:x}}', detail: 'Square root' },
  { label: '\\sqrt[n]', insertText: '\\sqrt[${1:n}]{${2:x}}', detail: 'n-th root' },
  { label: '\\binom', insertText: '\\binom{${1:n}}{${2:k}}', detail: 'Binomial coefficient' },

  // -- Sums, integrals, products --
  { label: '\\sum', insertText: '\\sum_{${1:i}=${2:0}}^{${3:n}}', detail: 'Sum' },
  { label: '\\int', insertText: '\\int_{${1:0}}^{${2:\\infty}}', detail: 'Definite integral' },
  { label: '\\iint', insertText: '\\iint', detail: 'Double integral' },
  { label: '\\iiint', insertText: '\\iiint', detail: 'Triple integral' },
  { label: '\\oint', insertText: '\\oint', detail: 'Contour integral' },
  { label: '\\prod', insertText: '\\prod_{${1:i}=${2:0}}^{${3:n}}', detail: 'Product' },
  { label: '\\lim', insertText: '\\lim_{${1:x \\to \\infty}}', detail: 'Limit' },

  // -- Elementary functions --
  { label: '\\log', insertText: '\\log' },
  { label: '\\ln', insertText: '\\ln' },
  { label: '\\sin', insertText: '\\sin' },
  { label: '\\cos', insertText: '\\cos' },
  { label: '\\tan', insertText: '\\tan' },
  { label: '\\csc', insertText: '\\csc' },
  { label: '\\sec', insertText: '\\sec' },
  { label: '\\cot', insertText: '\\cot' },
  { label: '\\arcsin', insertText: '\\arcsin' },
  { label: '\\arccos', insertText: '\\arccos' },
  { label: '\\arctan', insertText: '\\arctan' },
  { label: '\\sinh', insertText: '\\sinh' },
  { label: '\\cosh', insertText: '\\cosh' },
  { label: '\\tanh', insertText: '\\tanh' },
  { label: '\\sup', insertText: '\\sup' },
  { label: '\\inf', insertText: '\\inf' },
  { label: '\\max', insertText: '\\max' },
  { label: '\\min', insertText: '\\min' },
  { label: '\\gcd', insertText: '\\gcd' },

  // -- Auto-sizing brackets --
  { label: '\\left(', insertText: '\\left( ${1:x} \\right)', detail: 'Parentheses' },
  { label: '\\left[', insertText: '\\left[ ${1:x} \\right]', detail: 'Brackets' },
  { label: '\\left\\{', insertText: '\\left\\{ ${1:x} \\right\\}', detail: 'Braces' },
  { label: '\\langle', insertText: '\\langle ${1:x} \\rangle', detail: 'Angle brackets' },
  { label: '\\lvert', insertText: '\\lvert ${1:x} \\rvert', detail: 'Absolute value' },
  { label: '\\lVert', insertText: '\\lVert ${1:x} \\rVert', detail: 'Norm' },

  // -- Common symbols --
  { label: '\\infty', insertText: '\\infty' },
  { label: '\\partial', insertText: '\\partial' },
  { label: '\\nabla', insertText: '\\nabla' },
  { label: '\\forall', insertText: '\\forall' },
  { label: '\\exists', insertText: '\\exists' },
  { label: '\\nexists', insertText: '\\nexists' },
  { label: '\\neg', insertText: '\\neg' },
  { label: '\\emptyset', insertText: '\\emptyset' },
  { label: '\\varnothing', insertText: '\\varnothing' },
  { label: '\\cdot', insertText: '\\cdot' },
  { label: '\\cdots', insertText: '\\cdots' },
  { label: '\\vdots', insertText: '\\vdots' },
  { label: '\\ddots', insertText: '\\ddots' },
  { label: '\\times', insertText: '\\times' },
  { label: '\\div', insertText: '\\div' },
  { label: '\\pm', insertText: '\\pm' },
  { label: '\\mp', insertText: '\\mp' },
  { label: '\\cdot', insertText: '\\cdot' },
  { label: '\\ast', insertText: '\\ast' },
  { label: '\\star', insertText: '\\star' },
  { label: '\\circ', insertText: '\\circ' },
  { label: '\\bullet', insertText: '\\bullet' },
  { label: '\\oplus', insertText: '\\oplus' },
  { label: '\\otimes', insertText: '\\otimes' },
  { label: '\\odot', insertText: '\\odot' },
  { label: '\\to', insertText: '\\to' },
  { label: '\\mapsto', insertText: '\\mapsto' },

  // -- Relations --
  { label: '\\implies', insertText: '\\implies' },
  { label: '\\impliedby', insertText: '\\impliedby' },
  { label: '\\iff', insertText: '\\iff' },
  { label: '\\approx', insertText: '\\approx' },
  { label: '\\equiv', insertText: '\\equiv' },
  { label: '\\sim', insertText: '\\sim' },
  { label: '\\simeq', insertText: '\\simeq' },
  { label: '\\cong', insertText: '\\cong' },
  { label: '\\propto', insertText: '\\propto' },
  { label: '\\perp', insertText: '\\perp' },
  { label: '\\parallel', insertText: '\\parallel' },
  { label: '\\neq', insertText: '\\neq' },
  { label: '\\leq', insertText: '\\leq' },
  { label: '\\geq', insertText: '\\geq' },
  { label: '\\ll', insertText: '\\ll' },
  { label: '\\gg', insertText: '\\gg' },
  { label: '\\lll', insertText: '\\lll' },
  { label: '\\ggg', insertText: '\\ggg' },

  // -- Set notation --
  { label: '\\subset', insertText: '\\subset' },
  { label: '\\supset', insertText: '\\supset' },
  { label: '\\subseteq', insertText: '\\subseteq' },
  { label: '\\supseteq', insertText: '\\supseteq' },
  { label: '\\subsetneq', insertText: '\\subsetneq' },
  { label: '\\in', insertText: '\\in' },
  { label: '\\notin', insertText: '\\notin' },
  { label: '\\ni', insertText: '\\ni' },
  { label: '\\cap', insertText: '\\cap' },
  { label: '\\cup', insertText: '\\cup' },
  { label: '\\setminus', insertText: '\\setminus' },
  { label: '\\mathbb{R}', insertText: '\\mathbb{R}', detail: 'Real numbers' },
  { label: '\\mathbb{N}', insertText: '\\mathbb{N}', detail: 'Natural numbers' },
  { label: '\\mathbb{Z}', insertText: '\\mathbb{Z}', detail: 'Integers' },
  { label: '\\mathbb{Q}', insertText: '\\mathbb{Q}', detail: 'Rationals' },
  { label: '\\mathbb{C}', insertText: '\\mathbb{C}', detail: 'Complex numbers' },

  // -- Arrows --
  { label: '\\rightarrow', insertText: '\\rightarrow' },
  { label: '\\leftarrow', insertText: '\\leftarrow' },
  { label: '\\Rightarrow', insertText: '\\Rightarrow' },
  { label: '\\Leftarrow', insertText: '\\Leftarrow' },
  { label: '\\leftrightarrow', insertText: '\\leftrightarrow' },
  { label: '\\Leftrightarrow', insertText: '\\Leftrightarrow' },
  { label: '\\uparrow', insertText: '\\uparrow' },
  { label: '\\downarrow', insertText: '\\downarrow' },
  { label: '\\updownarrow', insertText: '\\updownarrow' },
  { label: '\\longrightarrow', insertText: '\\longrightarrow' },
  { label: '\\longleftarrow', insertText: '\\longleftarrow' },

  // -- Accents --
  { label: '\\hat', insertText: '\\hat{${1:x}}', detail: 'Hat' },
  { label: '\\bar', insertText: '\\bar{${1:x}}', detail: 'Bar' },
  { label: '\\vec', insertText: '\\vec{${1:x}}', detail: 'Vector' },
  { label: '\\dot', insertText: '\\dot{${1:x}}', detail: 'Dot' },
  { label: '\\ddot', insertText: '\\ddot{${1:x}}', detail: 'Double dot' },
  { label: '\\tilde', insertText: '\\tilde{${1:x}}', detail: 'Tilde' },
  { label: '\\widehat', insertText: '\\widehat{${1:x}}', detail: 'Wide hat' },
  { label: '\\widetilde', insertText: '\\widetilde{${1:x}}', detail: 'Wide tilde' },
  { label: '\\overline', insertText: '\\overline{${1:x}}', detail: 'Overline' },
  { label: '\\underline', insertText: '\\underline{${1:x}}', detail: 'Underline' },

  // -- Environments --
  { label: '\\begin{pmatrix}', insertText: '\\begin{pmatrix}\n\t${1}\n\\end{pmatrix}', detail: 'Matrix (parentheses)' },
  { label: '\\begin{bmatrix}', insertText: '\\begin{bmatrix}\n\t${1}\n\\end{bmatrix}', detail: 'Matrix (brackets)' },
  { label: '\\begin{Bmatrix}', insertText: '\\begin{Bmatrix}\n\t${1}\n\\end{Bmatrix}', detail: 'Matrix (braces)' },
  { label: '\\begin{vmatrix}', insertText: '\\begin{vmatrix}\n\t${1}\n\\end{vmatrix}', detail: 'Determinant' },
  { label: '\\begin{cases}', insertText: '\\begin{cases}\n\t${1}\n\\end{cases}', detail: 'Cases' },
  { label: '\\begin{aligned}', insertText: '\\begin{aligned}\n\t${1}\n\\end{aligned}', detail: 'Aligned equations' },
  { label: '\\begin{array}', insertText: '\\begin{array}{${1:c}}\n\t${2}\n\\end{array}', detail: 'Custom array' },
  { label: '\\begin{align}', insertText: '\\begin{align}\n\t${1}\n\\end{align}', detail: 'Align env' },

  // -- Text formatting --
  { label: '\\text', insertText: '\\text{${1:text}}', detail: 'Normal text in math' },
  { label: '\\mathrm', insertText: '\\mathrm{${1:x}}', detail: 'Roman font' },
  { label: '\\mathbf', insertText: '\\mathbf{${1:x}}', detail: 'Bold' },
  { label: '\\mathit', insertText: '\\mathit{${1:x}}', detail: 'Italic' },
  { label: '\\mathbb', insertText: '\\mathbb{${1:R}}', detail: 'Blackboard bold' },
  { label: '\\mathcal', insertText: '\\mathcal{${1:X}}', detail: 'Calligraphic' },
  { label: '\\mathfrak', insertText: '\\mathfrak{${1:X}}', detail: 'Fraktur' },
  { label: '\\mathscr', insertText: '\\mathscr{${1:X}}', detail: 'Script' },
  { label: '\\mathsf', insertText: '\\mathsf{${1:x}}', detail: 'Sans-serif' },
  { label: '\\mathtt', insertText: '\\mathtt{${1:x}}', detail: 'Typewriter' },

  // -- Spaces --
  { label: '\\;', insertText: '\\;', detail: 'Thick space' },
  { label: '\\:', insertText: '\\:', detail: 'Medium space' },
  { label: '\\,', insertText: '\\,', detail: 'Thin space' },
  { label: '\\!', insertText: '\\!', detail: 'Negative thin space' },
  { label: '\\quad', insertText: '\\quad', detail: '1em space' },
  { label: '\\qquad', insertText: '\\qquad', detail: '2em space' },
];
